apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: wg-easy
  name: wg-easy
  namespace: wg
spec:
  replicas: 1
  selector:
    matchLabels:
      service: wg-easy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: wg-easy
    spec:
      # hostNetwork: true
      containers:
        - image: ghcr.io/wg-easy/wg-easy:15
          name: wg-easy
          ports:
            - containerPort: 80
              protocol: UDP
              hostPort: 80
            - containerPort: 51821
              protocol: TCP
          securityContext:
            privileged: true
            # capabilities:
            #   add:
            #     - NET_ADMIN
            #     - NET_RAW
            #   drop:
            #     - ALL
          volumeMounts:
            - mountPath: /etc/wireguard
              name: etc-wireguard
      restartPolicy: Always
      volumes:
        - name: etc-wireguard
          persistentVolumeClaim:
            claimName: etc-wireguard
