apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway-shared
  namespace: kube-system
  # annotations:
  #   cert-manager.io/issuer: letsencrypt-dns01-prod
spec:
  gatewayClassName: cilium
  addresses:
    - type: IPAddress
      value: 10.0.0.21
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: "*.k8s.garden"
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.k8s.garden"
      allowedRoutes:
        namespaces:
          from: All
      # tls:
      #   mode: Terminate
      #   certificateRefs:
      #     - name: letsencrypt-dns01