apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway-shared
  namespace: kube-system
  annotations:
    cert-manager.io/clusterissuer: letsencrypt-dns01-staging
spec:
  gatewayClassName: cilium
  addresses:
    - type: IPAddress
      value: 10.0.0.21
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    # - name: https-k8s-garden
    #   protocol: HTTPS
    #   port: 443
    #   hostname: "*.k8s.garden"
    #   allowedRoutes:
    #     namespaces:
    #       from: All
    #   tls:
    #     mode: Terminate
    #     certificateRefs:
    #       - name: k8s-garden-letsencrypt-dns01
    # - name: https-noreplay-org
    #   protocol: HTTPS
    #   port: 443
    #   hostname: "plex.noreplay.org"
    #   allowedRoutes:
    #     namespaces:
    #       from: All
    #   tls:
    #     mode: Terminate
    #     certificateRefs:
    #       - name: noreplay-org-letsencrypt-dns01