# apiVersion: "cilium.io/v2"
# kind: CiliumClusterwideNetworkPolicy
# metadata:
#   name: "host-firewall"
# spec:
#   description: "Basic host firewall rules"
#   nodeSelector:
#     matchLabels:
#       kubernetes.io/hostname: cp-0
#   ingress:
#     - fromCIDRSet:
#         - cidr: 10.0.0.0/16
#     - fromCIDRSet:
#         - cidr: ff02::/64
#     - fromCIDRSet:
#         - cidr: fe80::/64
