apiVersion: v1
kind: Service
metadata:
  name: iperf3-server
  namespace: observability
spec:
  ports:
    - port: 5201
      protocol: TCP
      targetPort: 5201
  selector:
    service: iperf3-server
  type: LoadBalancer