apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns01-prod
  namespace: kube-system
spec:
  acme:
    email: letsencrypt-issuer@untersander.dev
    privateKeySecretRef:
      name: acme-dns01-prod-issuer-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns01-staging
  namespace: kube-system
spec:
  acme:
    email: letsencrypt-issuer@untersander.dev
    privateKeySecretRef:
      name: acme-dns01-staging-issuer-account-key
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token