# yaml-language-server: $schema=https://raw.githubusercontent.com/cilium/cilium/refs/heads/main/install/kubernetes/cilium/values.schema.json
# Talos Guide Settings: https://docs.siderolabs.com/kubernetes-guides/cni/deploying-cilium
devices: br+,enp+
nodePort:
  directRoutingDevice: br+
ipam:
  mode: kubernetes
kubeProxyReplacement: true
securityContext:
  capabilities:
    ciliumAgent: [CHOWN, KILL, NET_ADMIN, NET_RAW, IPC_LOCK, SYS_ADMIN, SYS_RESOURCE, DAC_OVERRIDE, FOWNER, SETGID, SETUID]
    cleanCiliumState: [NET_ADMIN, SYS_ADMIN, SYS_RESOURCE]
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
k8sServiceHost: localhost
k8sServicePort: 7445

# Debug
# debug:
#   enabled: true
#   verbose: flow

# Gateway API support
gatewayAPI:
  enabled: true
  # enableAlpn: true
  # enableAppProtocol: true
  # secretsNamespace:
  #   create: true
  #   name: "cilium-secrets"
# envoy:
#   enabled: true

# Ingress Support for backward compatibility with older applications
# ingressController:
#   enabled: true
#   loadbalancerMode: shared

ipv4:
  enabled: true
# IPv6 support
ipv6:
  enabled: true

# Use PodCIDR from Kubernetes node resource
k8s:
  # -- requireIPv4PodCIDR enables waiting for Kubernetes to provide the PodCIDR
  # range via the Kubernetes node resource
  requireIPv4PodCIDR: true
  # -- requireIPv6PodCIDR enables waiting for Kubernetes to provide the PodCIDR
  # range via the Kubernetes node resource
  requireIPv6PodCIDR: true

# Performance Tuning: https://docs.cilium.io/en/stable/operations/performance/tuning/
# routingMode: native
# bpf:
#   datapathMode: netkit
#   masquerade: true
#   distributedLRU:
#     enabled: true
#   mapDynamicSizeRatio: 0.08
# bpfClockProbe: true
# ipv4NativeRoutingCIDR: 10.244.0.0/24
# enableIPv4BIGTCP: true
# enableIPv4Masquerade: true
# enableIPmasqAgent: true
# ipv6NativeRoutingCIDR: fd00:10:244::/64
# enableIPv6BIGTCP: true
# enableIPv6Masquerade: true
# enableIPv6masqAgent: true

# L2 external load balancer support
l2announcements:
  enabled: true
k8sClientRateLimit:
  burst: 90
  qps: 60

# Multus
# cni:
#   exclusive: true

# Firewall
# hostFirewall:
#   enabled: true

# Observability
operator:
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  dashboards:
    enabled: true
    annotations:
      grafana_folder: Cilium
  replicas: 1
dashboards:
  enabled: true
  annotations:
    grafana_folder: Cilium
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
hubble:
  metrics:
    serviceMonitor:
      enabled: true
    enableOpenMetrics: true
    # https://docs.cilium.io/en/stable/observability/metrics/#hubble-exported-metrics
    enabled:
      - "dns:labelsContext=source_namespace,destination_namespace"
      - "drop:labelsContext=source_namespace,destination_namespace"
      - "flow:labelsContext=source_namespace,destination_namespace;sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity"
      - "httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction;sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity"
      - "icmp:labelsContext=source_namespace,destination_namespace;sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity"
      - "port-distribution:labelsContext=source_namespace,destination_namespace"
      - "tcp:labelsContext=source_namespace,destination_namespace"
      - "policy:labelsContext=source_namespace,destination_namespace;sourceContext=app|workload-name|pod|reserved-identity;destinationContext=app|workload-name|pod|dns|reserved-identity"
    dashboards:
      enabled: true
      annotations:
        grafana_folder: Cilium
  relay:
    enabled: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
