# -- Whether the operator should watch cluster CRD in its own namespace or not
currentNamespaceOnly: true

# -- Runs Ceph Pods as privileged to be able to write to `hostPaths` in OpenShift with SELinux restrictions.
hostpathRequiresPrivileged: true
