apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pihole
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      service: pihole
  template:
    metadata:
      labels:
        service: pihole
    spec:
      containers:
        - env:
            - name: FTLCONF_dns_listeningMode
              value: ALL
            - name: FTLCONF_dns_hosts
              value: "10.0.0.5 pihole.home"
            - name: FTLCONF_dns_domain_name
              value: home
            - name: FTLCONF_ntp_ipv4_active
              value: "false"
            - name: FTLCONF_ntp_ipv6_active
              value: "false"
            - name: FTLCONF_ntp_sync_active
              value: "false"
            - name: TZ
              value: Europe/Zurich
            - name: FTLCONF_dhcp_active
              value: "true"
            - name: FTLCONF_dhcp_start
              value: "10.0.0.50"
            - name: FTLCONF_dhcp_end
              value: "10.0.0.200"
            - name: FTLCONF_dhcp_router
              value: "10.0.0.1"
            - name: FTLCONF_dhcp_netmask
              value: "255.255.255.0"
            - name: FTLCONF_dhcp_ipv6
              value: "true"
            - name: FTLCONF_dhcp_rapidCommit
              value: "true"
            - name: FTLCONF_dhcp_multiDNS
              value: "false"
            - name: FTLCONF_misc_dnsmasq_lines
              value: "dhcp-option=option:dns-server,10.0.0.5"
          envFrom:
            - secretRef:
                name: pihole-webserver-api-secret
          image: pihole/pihole:2025.10.3
          name: pihole
          ports:
            - containerPort: 53
              hostPort: 53
              hostIP: 10.0.0.4
              protocol: UDP
            - containerPort: 67
              protocol: UDP
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_NICE
          volumeMounts:
            - mountPath: /etc/pihole
              name: pihole-config
      restartPolicy: Always
      volumes:
        - name: pihole-config
          persistentVolumeClaim:
            claimName: pihole-config
